Header header

bool controlling
uint8 queue
string current
string next

float32 reference_x
float32 reference_y
float32 reference_z
float32 reference_yaw

float32 target_x
float32 target_y
float32 target_z
float32 target_yaw

float32 ptam_x
float32 ptam_y
float32 ptam_z
float32 ptam_yaw

float32 error_x
float32 error_y
float32 error_z
float32 error_yaw
float32 error_dist

float32 roll
float32 pitch
float32 gaz
float32 yaw
